export const data = [
  { image: '/images/components-image/card-list/card-1.png', name: "Card 1", star: 1, buttonRemove: 'Remove', wishlist: 'no', type: 'REWARD', parentType: "CREDIT", dataIndex: "eddac978-0730-43ff-b919-de40d3ae1a05" },
  { image: '/images/components-image/card-list/card-1.png', name: "Card 2", star: 2, buttonRemove: 'Remove', wishlist: 'yes', type: 'DEBIT 1', parentType: "DEBIT", dataIndex: "5e55695d-e160-4c34-9a81-bfff08351b7c" },
  { image: '/images/components-image/card-list/card-1.png', name: "Card 3", star: 3, buttonRemove: 'Remove', wishlist: 'yes', type: 'REWARD', parentType: "CREDIT", dataIndex: "e824237c-9ed9-499e-a028-024f3abda76e" },
  { image: '/images/components-image/card-list/card-1.png', name: "Card 4", star: 4, buttonRemove: 'Remove', wishlist: 'no', type: 'REWARD', parentType: "CREDIT", dataIndex: "4" },
  { image: '/images/components-image/card-list/card-1.png', name: "Card 5", star: 5, buttonRemove: 'Remove', wishlist: 'yes', type: 'DEBIT 2', parentType: "DEBIT", dataIndex: "5" },
  { image: '/images/components-image/card-list/card-1.png', name: "Card 6", star: 1, buttonRemove: 'Remove', wishlist: 'no', type: 'CASHBACK', parentType: "CREDIT", dataIndex: "6" },
  { image: '/images/components-image/card-list/card-1.png', name: "Card 7", star: 2, buttonRemove: 'Remove', wishlist: 'yes', type: 'DEBIT 2', parentType: "DEBIT", dataIndex: "7" },
  { image: '/images/components-image/card-list/card-1.png', name: "Card 8", star: 3, buttonRemove: 'Remove', wishlist: 'no', type: 'DEBIT 1', parentType: "DEBIT", dataIndex: "8" },
  { image: '/images/components-image/card-list/card-1.png', name: "Card 9", star: 4, buttonRemove: 'Remove', wishlist: 'no', type: 'MILES', parentType: "CREDIT", dataIndex: "9" },
  { image: '/images/components-image/card-list/card-1.png', name: "Card 10", star: 5, buttonRemove: 'Remove', wishlist: 'yes', type: 'DEBIT 3', parentType: "DEBIT", dataIndex: "10" },
  { image: '/images/components-image/card-list/card-1.png', name: "Card 11", star: 1, buttonRemove: 'Remove', wishlist: 'yes', type: 'DEBIT 1', parentType: "DEBIT", dataIndex: "11" },
  { image: '/images/components-image/card-list/card-1.png', name: "Card 12", star: 2, buttonRemove: 'Remove', wishlist: 'no', type: 'DEBIT 3', parentType: "DEBIT", dataIndex: "12" },
  { image: '/images/components-image/card-list/card-1.png', name: "Card 13", star: 3, buttonRemove: 'Remove', wishlist: 'yes', type: 'MILES', parentType: "CREDIT", dataIndex: "13" },
  { image: '/images/components-image/card-list/card-1.png', name: "Card 14", star: 4, buttonRemove: 'Remove', wishlist: 'no', type: 'MILES', parentType: "CREDIT", dataIndex: "14" },
  { image: '/images/components-image/card-list/card-1.png', name: "Card 15", star: 5, buttonRemove: 'Remove', wishlist: 'yes', type: 'REWARD', parentType: "CREDIT", dataIndex: "15" },
  { image: '/images/components-image/card-list/card-1.png', name: "Card 16", star: 1, buttonRemove: 'Remove', wishlist: 'no', type: 'CASHBACK', parentType: "CREDIT", dataIndex: "16" },
  { image: '/images/components-image/card-list/card-1.png', name: "Card 17", star: 2, buttonRemove: 'Remove', wishlist: 'yes', type: 'CASHBACK', parentType: "CREDIT", dataIndex: "17" },
  { image: '/images/components-image/card-list/card-1.png', name: "Card 18", star: 3, buttonRemove: 'Remove', wishlist: 'no', type: 'DEBIT 2', parentType: "DEBIT", dataIndex: "18" },
  { image: '/images/components-image/card-list/card-1.png', name: "Card 19", star: 3, buttonRemove: 'Remove', wishlist: 'no', type: 'DEBIT 2', parentType: "DEBIT", dataIndex: "19" },
  { image: '/images/components-image/card-list/card-1.png', name: "Card 20", star: 3, buttonRemove: 'Remove', wishlist: 'no', type: 'DEBIT 2', parentType: "DEBIT", dataIndex: "20" },
  { image: '/images/components-image/card-list/card-1.png', name: "Card 21", star: 3, buttonRemove: 'Remove', wishlist: 'no', type: 'POINT', parentType: "POINT", dataIndex: "21" },
]