export const SUPPORT_NOW_SEGEMENT_TYPE = '[SUPPORT_NOW] SEGEMENT TYPE';

export const SUPPORT_NOW_GET_NO_TYPE = '[SUPPORT NOW] GET NO TYPE';
export const SUPPORT_NOW_GET_NO_TYPE_SUCCESS = '[SUPPORT NOW] GET NO TYPE SUCCESS';
export const SUPPORT_NOW_GET_NO_TYPE_FAIL = '[SUPPORT NOW] GET NO TYPE FAIL';

export const SUPPORT_NOW_GET_HAS_TYPE = '[SUPPORT NOW] GET HAS TYPE';
export const SUPPORT_NOW_GET_HAS_TYPE_SUCCESS = '[SUPPORT NOW] GET HAS TYPE SUCCESS';
export const SUPPORT_NOW_GET_HAS_TYPE_FAIL = '[SUPPORT NOW] GET HAS TYPE FAIL';

export const SUPPORT_NOW_GET_MENU_SUCCESS = '[SUPPORT NOW] GET MENU SUCCESS';
export const SUPPORT_NOW_GET_MENU_FAIL = '[SUPPORT NOW] GET MENU FAIL';

export const SUPPORT_NOW_RESET_SEGMENT = '[SUPPORT_NOW] RESET SEGEMENT';


