export const SUPPORT_NOW_SEGEMENT_TYPE = '[SUPPORT_NOW] SEGEMENT TYPE';
export const SUPPORT_NOW_GET_NO_TYPE = '[SUPPORT NOW] GET NO TYPE';
export const SUPPORT_NOW_GET_NO_TYPE_SUCCESS = '[SUPPORT NOW] GET NO TYPE SUCCESS';
export const SUPPORT_NOW_GET_NO_TYPE_FAIL = '[SUPPORT NOW] GET NO TYPE FAIL';
